// <auto-generated />
using System;
using CatalogoAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoAPI.Migrations
{
    [DbContext(typeof(AppDbContextCatalogoApi))]
    [Migration("20250720042007_SqlServerCatalogoApi")]
    partial class SqlServerCatalogoApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoAPI.Models.Categoria", b =>
                {
                    b.Property<long>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Handle"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Handle");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("CatalogoAPI.Models.ImagemProduto", b =>
                {
                    b.Property<long>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Handle"));

                    b.Property<long?>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Handle");

                    b.HasIndex("ProdutoId");

                    b.ToTable("imagensprodutos");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Marca", b =>
                {
                    b.Property<long>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Handle"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Handle");

                    b.ToTable("marcas");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Produto", b =>
                {
                    b.Property<long>("Handle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Handle"));

                    b.Property<long?>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Estoque")
                        .HasColumnType("bigint");

                    b.Property<long?>("MarcaId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Handle");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("CatalogoAPI.Models.ImagemProduto", b =>
                {
                    b.HasOne("CatalogoAPI.Models.Produto", "Produto")
                        .WithMany("ImagemProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Produto", b =>
                {
                    b.HasOne("CatalogoAPI.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogoAPI.Models.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Marca", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("CatalogoAPI.Models.Produto", b =>
                {
                    b.Navigation("ImagemProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
